version: "3.8"

services:
  food-service:
    image: jrojowski/fitatu-food-information:0.0.2-SNAPSHOT
    restart: always
    ports:
      - "8000:8000"
    environment:
      spring.profiles.active: cloud
      spring.datasource.url: jdbc:mysql://mysqldb:3306/fitatu?allowPublicKeyRetrieval=true&useSSL=false
      spring.datasource.username: root
      spring.datasource.password: admin
      spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
      jpa.hibernate.ddl-auto: none
      eureka.client.service-url.defaultZone: http://naming-server:8761/eureka
      spring.zipkin.baseurl: http://zipkin-server:9411
    depends_on:
      - mysqldb
      - naming-server
      - api-gateway

  mysqldb:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: fitatu
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin

  naming-server:
    container_name: naming-server
    image: jrojowski/fitatu-naming-server:0.0.1-SNAPSHOT
    ports:
      - "8761:8761"

  api-gateway:
    container_name: api-gateway
    image: jrojowski/fitatu-api-gateway:0.0.1-SNAPSHOT
    ports:
      - "8765:8765"
    environment:
      eureka.client.service-url.defaultZone: http://naming-server:8761/eureka
      spring.zipkin.baseurl: http://zipkin-server:9411

  calories-service:
    container_name: calories-service
    image: jrojowski/fitatu-calories-service:0.0.1-SNAPSHOT
    ports:
      - "8100:8100"
    environment:
      eureka.client.service-url.defaultZone: http://naming-server:8761/eureka
      spring.zipkin.baseurl: http://zipkin-server:9411
    depends_on:
      - food-service
      - naming-server
      - api-gateway

  zipkin-server:
    container_name: zipkin-server
    image: openzipkin/zipkin:2.23
    ports:
      - "9411:9411"