server:
  port: 8000

spring:
  application:
    name: "food-service"
  datasource:
    url: "jdbc:mysql://localhost:3306/fitatu?allowPublicKeyRetrieval=true&useSSL=false"
    password: "admin"
    username: "root"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  liquibase:
    change-log: "classpath:liquibase/master.xml"
  jpa:
    hibernate:
      ddl-auto: none

management:
  endpoints:
    web:
      base-path: "/status"
      exposure:
        include: "*"