management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/fitatu?allowPublicKeyRetrieval=true&useSSL=false"
    username: "root"
    password: "admin"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: "classpath:liquibase/master.xml"
